package com.github.balotias.intellijantlers.editor

import com.intellij.lang.annotation.HighlightSeverity
import com.intellij.testFramework.fixtures.BasePlatformTestCase

/**
 * A `<script>`/`<style>` whose content is generated by Antlers can't be validly parsed by the injected
 * JS/CSS/JSON language — the `{{ }}` aren't valid in it. Those parse errors are false positives and are
 * suppressed (tested via JSON, the one injected language available in the test runtime; the suppression
 * is language-agnostic, so JS and CSS behave the same in the IDE).
 */
class AntlersScriptStyleHighlightTest : BasePlatformTestCase() {

    private fun errors(text: String): List<String> {
        myFixture.configureByText("p.antlers.html", text)
        return myFixture.doHighlighting()
            .filter { it.severity >= HighlightSeverity.WARNING }
            .map { it.description ?: "" }
    }

    // A JSON-LD <script> with Antlers conditionals / interpolations — no false JSON errors.
    fun testJsonLdScriptWithAntlersSuppressed() {
        val e = errors(
            "<script type=\"application/ld+json\">\n" +
                "{ \"a\": {{ count }}, {{ if x }}\"b\": 1{{ /if }} }\n" +
                "</script>"
        )
        assertTrue("Antlers-templated JSON script errors must be suppressed: $e", e.isEmpty())
    }

    // …but a genuine JSON error in a script with NO Antlers is still reported (no over-suppression).
    fun testPureJsonScriptErrorStillReported() {
        val e = errors("<script type=\"application/ld+json\">\n{ \"a\": , }\n</script>")
        assertTrue("a real JSON error (no Antlers in the block) must still be reported", e.isNotEmpty())
    }

    // The real-world shape: a JSON-LD graph built with a nested loop + conditional trailing commas
    // (Peak SEO breadcrumbs / schema) — all the JSON-structure errors that creates are suppressed.
    fun testNestedConditionalJsonLdSuppressed() {
        val e = errors(
            "<script type=\"application/ld+json\">\n" +
                "{\n" +
                "  \"@type\": \"BreadcrumbList\",\n" +
                "  \"itemListElement\": [\n" +
                "    {{ nav:breadcrumbs }}\n" +
                "      { \"position\": {{ count }}, \"name\": \"{{ title }}\" }{{ unless last }},{{ /unless }}\n" +
                "    {{ /nav:breadcrumbs }}\n" +
                "  ]\n" +
                "}\n" +
                "</script>"
        )
        assertTrue("nested-conditional JSON-LD must not produce false errors: $e", e.isEmpty())
    }

    // Suppression keys on Antlers being INSIDE the erroring block — a real JSON error in a script with
    // no Antlers is still reported even when the file has Antlers elsewhere.
    fun testScriptWithoutAntlersStillReportedEvenIfFileHasAntlers() {
        val e = errors("{{ title }}\n<script type=\"application/ld+json\">\n{ \"a\": , }\n</script>")
        assertTrue("a pure-JSON error must report even if the file has Antlers outside the block", e.isNotEmpty())
    }

    // A templated <style> is handled without false errors / exceptions (CSS path).
    fun testTemplatedStyleNoFalseErrors() {
        val e = errors("<style>\n.x { color: {{ color }}; width: {{ w }}px; }\n</style>")
        assertTrue("templated <style> must not produce errors: $e", e.isEmpty())
    }
}
