package com.github.balotias.intellijantlers.blueprint

data class SystemVariable(val name: String, val description: String)

/** Common Statamic variables available in most template contexts. */
object SystemVariables {
    val ALL: List<SystemVariable> = listOf(
        SystemVariable("title", "The title of the entry or page."),
        SystemVariable("url", "The URL of the entry."),
        SystemVariable("permalink", "The absolute URL of the entry."),
        SystemVariable("slug", "The URL slug of the entry."),
        SystemVariable("id", "The unique id of the entry."),
        SystemVariable("date", "The entry's date."),
        SystemVariable("last_modified", "When the entry was last modified."),
        SystemVariable("status", "draft, published, or scheduled."),
        SystemVariable("published", "Whether the entry is published."),
        SystemVariable("content", "The rendered main content."),
        SystemVariable("author", "The entry's author."),
        SystemVariable("template", "The template used to render."),
        SystemVariable("layout", "The layout used to render."),
        SystemVariable("collection", "The entry's collection handle."),
        SystemVariable("mount", "The entry the collection is mounted to."),
        SystemVariable("parent", "The parent entry in a structure."),
        SystemVariable("depth", "The depth in a structure tree."),
        SystemVariable("is_current", "Whether this is the current URL."),
        SystemVariable("is_parent", "Whether this is an ancestor of the current URL."),
        SystemVariable("now", "The current date/time."),
        SystemVariable("site", "The current site handle."),
        SystemVariable("locale", "The current locale."),
        SystemVariable("current_url", "The current request URL."),
        SystemVariable("current_uri", "The current request URI."),
        SystemVariable("csrf_token", "The CSRF token value."),
        SystemVariable("environment", "The application environment."),
        SystemVariable("template_content", "The rendered template content (output inside a layout)."),
        SystemVariable("current_template", "The template actually used to render the page."),
        SystemVariable("current_layout", "The layout actually used to render the page."),
        SystemVariable("current_user", "The authenticated user (null if logged out)."),
        SystemVariable("logged_in", "Whether the visitor is authenticated."),
        SystemVariable("homepage", "The site's homepage URL."),
        SystemVariable("is_homepage", "Whether the current URL is the homepage."),
        SystemVariable("last_segment", "The final segment of the current URL."),
        SystemVariable("segment_1", "The first URL segment (segment_2, segment_3, … follow)."),
        SystemVariable("csrf_field", "A hidden input field containing the CSRF token."),
        SystemVariable("config", "Access Statamic/Laravel configuration values."),
        SystemVariable("get", "Query-string variables."),
        SystemVariable("post", "Submitted POST data."),
        SystemVariable("old", "Old (previous-request) input, for re-populating forms after validation."),
        SystemVariable("response_code", "The HTTP response code (200 or 404)."),
        SystemVariable("live_preview", "Whether the page is rendering in Live Preview."),
        SystemVariable("edit_url", "Control-Panel edit URL for the current content."),
        SystemVariable("sites", "All configured sites."),
        SystemVariable("is_entry", "Whether the current content is an entry."),
        // Source-verified global cascade variables (statamic/cms View/Cascade.php).
        SystemVariable("get_post", "Combined GET and POST variables (POST takes precedence)."),
        SystemVariable("cp_url", "The URL to the Control Panel."),
        SystemVariable("current_date", "The current date/time (alias of now)."),
        SystemVariable("current_full_url", "The current request URL including query string."),
        SystemVariable("logged_out", "Whether the visitor is not authenticated."),
        SystemVariable("today", "Today's date."),
        SystemVariable("xml_header", "Outputs the XML declaration (for feeds/sitemaps).")
    )
}
