package com.github.balotias.intellijantlers.editor

import com.github.balotias.intellijantlers.AntlersLanguage
import com.github.balotias.intellijantlers.psi.AntlersStatement
import com.github.balotias.intellijantlers.template.AntlersFileViewProvider
import com.intellij.codeInsight.daemon.impl.HighlightInfo
import com.intellij.codeInsight.daemon.impl.HighlightInfoFilter
import com.intellij.lang.annotation.HighlightSeverity
import com.intellij.lang.html.HTMLLanguage
import com.intellij.lang.injection.InjectedLanguageManager
import com.intellij.openapi.util.TextRange
import com.intellij.psi.PsiFile
import com.intellij.psi.util.PsiTreeUtil
import com.intellij.psi.xml.XmlTag

/**
 * Suppresses false-positive *structural* HTML errors that arise when an Antlers interpolation acts as
 * (or sits inside) an HTML tag name — e.g. `<{{ as or 'h2' }}> … </{{ as or 'h2' }}>`.
 *
 * The template-data tree only sees opaque placeholders where the `{{ }}` are, so the HTML parser can't
 * pair `<placeholder>`/`</placeholder>` and reports "Closing tag matches nothing" (and the matching
 * "element is not closed"). These are spurious for Antlers templates.
 *
 * The suppression is narrow: it only drops the specific structural messages, only in Antlers view
 * providers, and only when the flagged range actually overlaps an Antlers `{{ }}` statement. A genuine
 * mismatch with no interpolation in range (`<div>…</span>`) is left untouched.
 */
class AntlersHtmlErrorFilter : HighlightInfoFilter {

    override fun accept(highlightInfo: HighlightInfo, file: PsiFile?): Boolean {
        file ?: return true
        val rawRange = TextRange(highlightInfo.startOffset, highlightInfo.endOffset)
        // Resolve to the Antlers host view provider + a host-coordinate range. The injected JS/CSS/JSON in
        // a <script>/<style> is highlighted as its own file, so for those infos `file` is the injected
        // fragment, not the Antlers host — map back through the injection.
        val (viewProvider, range) = when (val vp = file.viewProvider) {
            is AntlersFileViewProvider -> vp to rawRange
            else -> {
                val ilm = InjectedLanguageManager.getInstance(file.project)
                val hostVp = ilm.getInjectionHost(file)?.containingFile?.viewProvider as? AntlersFileViewProvider
                    ?: return true
                hostVp to ilm.injectedToHost(file, rawRange)
            }
        }
        val antlers = viewProvider.getPsi(AntlersLanguage.INSTANCE) ?: return true

        // A `<script>`/`<style>` whose content is generated by Antlers can't be validly parsed by its
        // injected JS/CSS/JSON language (the `{{ }}` aren't valid in it) — those parse errors are
        // spurious. Drop ERROR/WARNING infos inside such a block. Pure JS/CSS/JSON blocks (no Antlers)
        // keep their real diagnostics, and Antlers' own coloring (INFORMATION) is never touched.
        if (highlightInfo.severity >= HighlightSeverity.WARNING &&
            insideTemplatedScriptOrStyle(viewProvider, antlers, range)
        ) return false

        val description = highlightInfo.description ?: return true
        if (SUPPRESSED_FRAGMENTS.none { description.contains(it, ignoreCase = true) }) return true
        return !overlapsInterpolation(antlers, range)
    }

    /** True when [range] sits in a `<script>`/`<style>` tag that contains at least one Antlers `{{ }}`. */
    private fun insideTemplatedScriptOrStyle(
        viewProvider: AntlersFileViewProvider, antlers: PsiFile, range: TextRange
    ): Boolean {
        val html = viewProvider.getPsi(HTMLLanguage.INSTANCE) ?: return false
        val statements = PsiTreeUtil.findChildrenOfType(antlers, AntlersStatement::class.java)
        if (statements.isEmpty()) return false
        return PsiTreeUtil.findChildrenOfType(html, XmlTag::class.java).any { tag ->
            (tag.name.equals("script", ignoreCase = true) || tag.name.equals("style", ignoreCase = true)) &&
                tag.textRange.intersects(range) &&
                statements.any { tag.textRange.contains(it.textRange) }
        }
    }

    private fun overlapsInterpolation(antlers: PsiFile, range: TextRange): Boolean =
        PsiTreeUtil.findChildrenOfType(antlers, AntlersStatement::class.java)
            .any { it.textRange.intersects(range) }

    companion object {
        /** Substrings of the HTML structural errors produced by an interpolated tag name. */
        private val SUPPRESSED_FRAGMENTS = listOf(
            "Closing tag matches nothing",
            "Closing tag name is missing",   // multi-line `</{{ … }}>` — HTML sees `</` then `{{`
            "is not closed",
        )
    }
}
