package com.github.balotias.intellijantlers.catalog

/** Bundled Statamic-6 modifier catalog (Kotlin data — no runtime JSON parser). Extend here. */
object CatalogModifiers {
    val ALL: List<ModifierDef> = listOf(
        ModifierDef(name = "upper", description = "Uppercase the value.", docUrl = "https://statamic.dev/modifiers/upper"),
        ModifierDef(name = "lower", description = "Lowercase the value.", docUrl = "https://statamic.dev/modifiers/lower"),
        ModifierDef(name = "title", description = "Title-case the value.", docUrl = "https://statamic.dev/modifiers/title"),
        ModifierDef(name = "ucfirst", description = "Capitalise the first letter.", docUrl = "https://statamic.dev/modifiers/ucfirst"),
        ModifierDef(name = "truncate", description = "Truncate to a length.", takesArguments = true,
            parameters = listOf(
                ModifierParam("length", "Maximum length to keep."),
                ModifierParam("ellipsis", "Appended when truncated.", optional = true, default = "'…'"),
            ),
            docUrl = "https://statamic.dev/modifiers/truncate"),
        ModifierDef(name = "limit", description = "Limit to N items/characters.", takesArguments = true,
            parameters = listOf(
                ModifierParam("count", "Maximum number of characters/items to keep."),
            ),
            docUrl = "https://statamic.dev/modifiers/limit"),
        ModifierDef(name = "raw", description = "Output without escaping.", docUrl = "https://statamic.dev/modifiers/raw"),
        ModifierDef(name = "markdown", description = "Render markdown.", docUrl = "https://statamic.dev/modifiers/markdown"),
        ModifierDef(name = "nl2br", description = "Convert newlines to <br>.", docUrl = "https://statamic.dev/modifiers/nl2br"),
        ModifierDef(name = "strip_tags", description = "Remove HTML tags.", takesArguments = true,
            parameters = listOf(
                ModifierParam("allowed", "Tags to keep, e.g. '<a><strong>'.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/strip_tags"),
        ModifierDef(name = "format", description = "Format a date.", takesArguments = true,
            parameters = listOf(
                ModifierParam("format", "PHP/Carbon date format string."),
            ),
            docUrl = "https://statamic.dev/modifiers/format"),
        ModifierDef(name = "relative", description = "Relative date, e.g. 3 days ago.", takesArguments = true,
            parameters = listOf(
                ModifierParam("from", "Date to compare against.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/relative"),
        ModifierDef(name = "count", description = "Count items.", docUrl = "https://statamic.dev/modifiers/count"),
        ModifierDef(name = "length", description = "Length of a string/array.", docUrl = "https://statamic.dev/modifiers/length"),
        ModifierDef(name = "first", description = "First item.", takesArguments = true,
            parameters = listOf(
                ModifierParam("count", "Number of items to take.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/first"),
        ModifierDef(name = "last", description = "Last item.", takesArguments = true,
            parameters = listOf(
                ModifierParam("count", "Number of items to take.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/last"),
        ModifierDef(name = "reverse", description = "Reverse a string/array.", docUrl = "https://statamic.dev/modifiers/reverse"),
        ModifierDef(name = "sort", description = "Sort an array.", takesArguments = true,
            parameters = listOf(
                ModifierParam("key", "Property to sort by; append ':desc' to reverse.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/sort"),
        ModifierDef(name = "where", description = "Filter an array by key/value.", takesArguments = true,
            parameters = listOf(
                ModifierParam("key", "Item property to test."),
                ModifierParam("value", "Value the property must equal."),
            ),
            docUrl = "https://statamic.dev/modifiers/where"),
        ModifierDef(name = "pluck", description = "Pluck a field from each item.", takesArguments = true,
            parameters = listOf(
                ModifierParam("key", "Property to pull from each item."),
            ),
            docUrl = "https://statamic.dev/modifiers/pluck"),
        ModifierDef(name = "join", description = "Join an array with a glue string.", takesArguments = true,
            parameters = listOf(
                ModifierParam("glue", "String placed between items."),
            ),
            docUrl = "https://statamic.dev/modifiers/join"),
        ModifierDef(name = "explode", description = "Split a string into an array.", takesArguments = true,
            parameters = listOf(
                ModifierParam("delimiter", "Boundary string to split on."),
            ),
            docUrl = "https://statamic.dev/modifiers/explode"),
        ModifierDef(name = "replace", description = "Replace a substring.", takesArguments = true,
            parameters = listOf(
                ModifierParam("search", "The substring to find."),
                ModifierParam("replacement", "The string to substitute in."),
            ),
            docUrl = "https://statamic.dev/modifiers/replace"),
        ModifierDef(name = "url", description = "The URL of an entry/asset.", takesArguments = true,
            parameters = listOf(
                ModifierParam("key", "Asset/relation key to resolve.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/url"),
        ModifierDef(name = "slugify", description = "Make a URL slug.", docUrl = "https://statamic.dev/modifiers/slugify"),
        ModifierDef(name = "ensure_left", description = "Prefix if missing.", takesArguments = true,
            parameters = listOf(
                ModifierParam("prefix", "Substring the value must start with."),
            ),
            docUrl = "https://statamic.dev/modifiers/ensure_left"),
        ModifierDef(name = "ensure_right", description = "Ensure the string ends with a suffix.", takesArguments = true,
            parameters = listOf(
                ModifierParam("suffix", "Substring the value must end with."),
            ),
            docUrl = "https://statamic.dev/modifiers/ensure_right"),
        ModifierDef(name = "embed_url", description = "Make an embeddable URL.", docUrl = "https://statamic.dev/modifiers/embed_url"),
        ModifierDef(name = "to_json", description = "Encode as JSON.", docUrl = "https://statamic.dev/modifiers/to_json"),
        ModifierDef(name = "format_localized", description = "Locale-aware date format.", takesArguments = true,
            parameters = listOf(
                ModifierParam("format", "strftime-style locale format string."),
            ),
            docUrl = "https://statamic.dev/modifiers/format_localized"),
        ModifierDef(name = "default", description = "Fallback when empty.", takesArguments = true,
            parameters = listOf(
                ModifierParam("fallback", "Value to use when the input is empty."),
            ),
            docUrl = "https://statamic.dev/modifiers/default"),
        // Additional modifiers from the full Statamic 6 core set (Appendix B)
        ModifierDef(name = "add", description = "Add to a number.", takesArguments = true,
            parameters = listOf(
                ModifierParam("value", "Number to add."),
            ),
            docUrl = "https://statamic.dev/modifiers/add"),
        ModifierDef(name = "add_slashes", description = "Backslash-escape quotes.", docUrl = "https://statamic.dev/modifiers/add_slashes"),
        ModifierDef(name = "ampersand_list", description = "Join with ampersands.", docUrl = "https://statamic.dev/modifiers/ampersand_list"),
        ModifierDef(name = "antlers", description = "Parse Antlers template syntax.", docUrl = "https://statamic.dev/modifiers/antlers"),
        ModifierDef(name = "ascii", description = "Convert to ASCII.", takesArguments = false, docUrl = "https://statamic.dev/modifiers/ascii"),
        ModifierDef(name = "as", description = "Alias to a variable name.", takesArguments = true,
            parameters = listOf(
                ModifierParam("alias", "Variable name to expose the value under."),
            ),
            docUrl = "https://statamic.dev/modifiers/as"),
        ModifierDef(name = "at", description = "Item at index.", takesArguments = true,
            parameters = listOf(
                ModifierParam("index", "Zero-based index of the item to return."),
            ),
            docUrl = "https://statamic.dev/modifiers/at"),
        ModifierDef(name = "attribute", description = "Extract HTML attribute.", takesArguments = true,
            parameters = listOf(
                ModifierParam("name", "HTML attribute to extract."),
            ),
            docUrl = "https://statamic.dev/modifiers/attribute"),
        ModifierDef(name = "background_position", description = "CSS background position.", takesArguments = true,
            parameters = listOf(
                ModifierParam("default", "Fallback position.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/background_position"),
        ModifierDef(name = "backspace", description = "Remove trailing chars.", takesArguments = true,
            parameters = listOf(
                ModifierParam("amount", "Number of trailing characters to remove."),
            ),
            docUrl = "https://statamic.dev/modifiers/backspace"),
        ModifierDef(name = "bard_html", description = "Bard data to HTML.", docUrl = "https://statamic.dev/modifiers/bard_html"),
        ModifierDef(name = "bard_items", description = "Bard items.", docUrl = "https://statamic.dev/modifiers/bard_items"),
        ModifierDef(name = "bard_text", description = "Bard plain text.", docUrl = "https://statamic.dev/modifiers/bard_text"),
        ModifierDef(name = "bool_string", description = "Boolean to string.", docUrl = "https://statamic.dev/modifiers/bool_string"),
        ModifierDef(name = "camelize", description = "To camelCase.", docUrl = "https://statamic.dev/modifiers/camelize"),
        ModifierDef(name = "cdata", description = "Wrap in CDATA.", docUrl = "https://statamic.dev/modifiers/cdata"),
        ModifierDef(name = "ceil", description = "Round up.", docUrl = "https://statamic.dev/modifiers/ceil"),
        ModifierDef(name = "chunk", description = "Split into chunks.", takesArguments = true,
            parameters = listOf(
                ModifierParam("size", "Items per chunk."),
            ),
            docUrl = "https://statamic.dev/modifiers/chunk"),
        ModifierDef(name = "classes", description = "Conditional CSS classes.", takesArguments = true,
            parameters = listOf(
                ModifierParam("classes", "Class names or conditional [class => bool] maps."),
            ),
            docUrl = "https://statamic.dev/modifiers/classes"),
        ModifierDef(name = "collapse", description = "Flatten one level / drop empties.", docUrl = "https://statamic.dev/modifiers/collapse"),
        ModifierDef(name = "collapse_whitespace", description = "Collapse whitespace.", docUrl = "https://statamic.dev/modifiers/collapse_whitespace"),
        ModifierDef(name = "compact", description = "Remove nulls.", docUrl = "https://statamic.dev/modifiers/compact"),
        ModifierDef(name = "contains", description = "Value present.", takesArguments = true,
            parameters = listOf(
                ModifierParam("value", "Value to look for."),
            ),
            docUrl = "https://statamic.dev/modifiers/contains"),
        ModifierDef(name = "contains_all", description = "All values present.", takesArguments = true,
            parameters = listOf(
                ModifierParam("values", "All values that must be present."),
            ),
            docUrl = "https://statamic.dev/modifiers/contains_all"),
        ModifierDef(name = "contains_any", description = "Any value present.", takesArguments = true,
            parameters = listOf(
                ModifierParam("values", "Values, any of which may be present."),
            ),
            docUrl = "https://statamic.dev/modifiers/contains_any"),
        ModifierDef(name = "console_log", description = "Console.log output.", docUrl = "https://statamic.dev/modifiers/console_log"),
        ModifierDef(name = "count_substring", description = "Substring occurrences.", takesArguments = true,
            parameters = listOf(
                ModifierParam("needle", "Substring to count."),
            ),
            docUrl = "https://statamic.dev/modifiers/count_substring"),
        ModifierDef(name = "dashify", description = "To dash-case.", docUrl = "https://statamic.dev/modifiers/dashify"),
        ModifierDef(name = "days_ago", description = "Days since date.", takesArguments = false, docUrl = "https://statamic.dev/modifiers/days_ago"),
        ModifierDef(name = "decode", description = "Decode entities.", takesArguments = false, docUrl = "https://statamic.dev/modifiers/decode"),
        ModifierDef(name = "deslugify", description = "Slug to text.", docUrl = "https://statamic.dev/modifiers/deslugify"),
        ModifierDef(name = "dl", description = "Definition-list markup.", docUrl = "https://statamic.dev/modifiers/dl"),
        ModifierDef(name = "doesnt_overlap", description = "Arrays share nothing.", takesArguments = true,
            parameters = listOf(
                ModifierParam("values", "Other array that must share nothing."),
            ),
            docUrl = "https://statamic.dev/modifiers/doesnt_overlap"),
        ModifierDef(name = "divide", description = "Division.", takesArguments = true,
            parameters = listOf(
                ModifierParam("value", "Number to divide by."),
            ),
            docUrl = "https://statamic.dev/modifiers/divide"),
        ModifierDef(name = "dump", description = "Debug output.", docUrl = "https://statamic.dev/modifiers/dump"),
        ModifierDef(name = "entities", description = "Encode HTML entities.", docUrl = "https://statamic.dev/modifiers/entities"),
        ModifierDef(name = "excerpt", description = "Summary excerpt.", takesArguments = true,
            parameters = listOf(
                ModifierParam("start", "Marker for the excerpt start.", optional = true),
                ModifierParam("end", "Marker for the excerpt end.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/excerpt"),
        ModifierDef(name = "favicon", description = "Favicon link tag.", takesArguments = true,
            parameters = listOf(
                ModifierParam("rel", "rel attribute.", optional = true, default = "'icon'"),
            ),
            docUrl = "https://statamic.dev/modifiers/favicon"),
        ModifierDef(name = "filter_empty", description = "Drop empties.", docUrl = "https://statamic.dev/modifiers/filter_empty"),
        ModifierDef(name = "flatten", description = "Flatten array.", docUrl = "https://statamic.dev/modifiers/flatten"),
        ModifierDef(name = "flip", description = "Swap keys/values.", docUrl = "https://statamic.dev/modifiers/flip"),
        ModifierDef(name = "floor", description = "Round down.", docUrl = "https://statamic.dev/modifiers/floor"),
        ModifierDef(name = "format_number", description = "Localized number.", takesArguments = true,
            parameters = listOf(
                ModifierParam("precision", "Decimal places.", optional = true, default = "0"),
            ),
            docUrl = "https://statamic.dev/modifiers/format_number"),
        ModifierDef(name = "format_translated", description = "Translated date format.", takesArguments = true,
            parameters = listOf(
                ModifierParam("format", "Date format with translated month/day names."),
            ),
            docUrl = "https://statamic.dev/modifiers/format_translated"),
        ModifierDef(name = "full_urls", description = "Relative to absolute URLs.", takesArguments = true,
            parameters = listOf(
                ModifierParam("base", "Base URL to prepend.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/full_urls"),
        ModifierDef(name = "get", description = "Value by key.", takesArguments = true,
            parameters = listOf(
                ModifierParam("key", "Key whose value to return."),
                ModifierParam("default", "Fallback when the key is missing.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/get"),
        ModifierDef(name = "gravatar", description = "Gravatar URL.", takesArguments = true,
            parameters = listOf(
                ModifierParam("size", "Pixel size of the avatar.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/gravatar"),
        ModifierDef(name = "group_by", description = "Group items.", takesArguments = true,
            parameters = listOf(
                ModifierParam("key", "Property to group items by."),
            ),
            docUrl = "https://statamic.dev/modifiers/group_by"),
        ModifierDef(name = "headline", description = "Title-case headline.", docUrl = "https://statamic.dev/modifiers/headline"),
        ModifierDef(name = "hex_to_rgb", description = "Hex to RGB.", docUrl = "https://statamic.dev/modifiers/hex_to_rgb"),
        ModifierDef(name = "hours_ago", description = "Hours since.", takesArguments = true,
            parameters = listOf(
                ModifierParam("date", "Date to measure from.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/hours_ago"),
        ModifierDef(name = "image", description = "Img tag.", takesArguments = true,
            parameters = listOf(
                ModifierParam("alt", "alt text for the <img>.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/image"),
        ModifierDef(name = "in_array", description = "Value in array.", takesArguments = true,
            parameters = listOf(
                ModifierParam("value", "Value to search for in the array."),
            ),
            docUrl = "https://statamic.dev/modifiers/in_array"),
        ModifierDef(name = "insert", description = "Insert at index.", takesArguments = true,
            parameters = listOf(
                ModifierParam("value", "Value to insert."),
                ModifierParam("index", "Position to insert at."),
            ),
            docUrl = "https://statamic.dev/modifiers/insert"),
        ModifierDef(name = "is_after", description = "Date after.", takesArguments = true,
            parameters = listOf(
                ModifierParam("date", "Date the value must be after."),
            ),
            docUrl = "https://statamic.dev/modifiers/is_after"),
        ModifierDef(name = "is_alpha", description = "Letters only.", docUrl = "https://statamic.dev/modifiers/is_alpha"),
        ModifierDef(name = "is_alphanumeric", description = "Alphanumeric only.", docUrl = "https://statamic.dev/modifiers/is_alphanumeric"),
        ModifierDef(name = "is_array", description = "Is array.", docUrl = "https://statamic.dev/modifiers/is_array"),
        ModifierDef(name = "is_before", description = "Date before.", takesArguments = true,
            parameters = listOf(
                ModifierParam("date", "Date the value must be before."),
            ),
            docUrl = "https://statamic.dev/modifiers/is_before"),
        ModifierDef(name = "is_between", description = "Within range.", takesArguments = true,
            parameters = listOf(
                ModifierParam("start", "Range start date."),
                ModifierParam("end", "Range end date."),
            ),
            docUrl = "https://statamic.dev/modifiers/is_between"),
        ModifierDef(name = "is_blank", description = "Empty/blank.", docUrl = "https://statamic.dev/modifiers/is_blank"),
        ModifierDef(name = "is_email", description = "Valid email.", docUrl = "https://statamic.dev/modifiers/is_email"),
        ModifierDef(name = "is_embeddable", description = "Embeddable URL.", docUrl = "https://statamic.dev/modifiers/is_embeddable"),
        ModifierDef(name = "is_external_url", description = "External URL.", docUrl = "https://statamic.dev/modifiers/is_external_url"),
        ModifierDef(name = "is_future", description = "Future date.", docUrl = "https://statamic.dev/modifiers/is_future"),
        ModifierDef(name = "is_json", description = "Valid JSON.", docUrl = "https://statamic.dev/modifiers/is_json"),
        ModifierDef(name = "is_leap_year", description = "Leap year.", docUrl = "https://statamic.dev/modifiers/is_leap_year"),
        ModifierDef(name = "is_lowercase", description = "All lowercase.", docUrl = "https://statamic.dev/modifiers/is_lowercase"),
        ModifierDef(name = "is_numberwang", description = "Is Numberwang.", docUrl = "https://statamic.dev/modifiers/is_numberwang"),
        ModifierDef(name = "is_numeric", description = "Numeric.", docUrl = "https://statamic.dev/modifiers/is_numeric"),
        ModifierDef(name = "is_past", description = "Past date.", docUrl = "https://statamic.dev/modifiers/is_past"),
        ModifierDef(name = "is_today", description = "Is today.", docUrl = "https://statamic.dev/modifiers/is_today"),
        ModifierDef(name = "is_tomorrow", description = "Is tomorrow.", docUrl = "https://statamic.dev/modifiers/is_tomorrow"),
        ModifierDef(name = "is_uppercase", description = "All uppercase.", docUrl = "https://statamic.dev/modifiers/is_uppercase"),
        ModifierDef(name = "is_url", description = "Valid URL.", docUrl = "https://statamic.dev/modifiers/is_url"),
        ModifierDef(name = "is_weekday", description = "Weekday.", docUrl = "https://statamic.dev/modifiers/is_weekday"),
        ModifierDef(name = "is_weekend", description = "Weekend.", docUrl = "https://statamic.dev/modifiers/is_weekend"),
        ModifierDef(name = "is_yesterday", description = "Is yesterday.", docUrl = "https://statamic.dev/modifiers/is_yesterday"),
        ModifierDef(name = "iso_format", description = "ISO date.", docUrl = "https://statamic.dev/modifiers/iso_format"),
        ModifierDef(name = "kebab", description = "To kebab-case.", docUrl = "https://statamic.dev/modifiers/kebab"),
        ModifierDef(name = "key_by", description = "Key by property.", takesArguments = true,
            parameters = listOf(
                ModifierParam("key", "Property to use as each item's key."),
            ),
            docUrl = "https://statamic.dev/modifiers/key_by"),
        ModifierDef(name = "keys", description = "Array keys.", docUrl = "https://statamic.dev/modifiers/keys"),
        ModifierDef(name = "lcfirst", description = "Lowercase first char.", docUrl = "https://statamic.dev/modifiers/lcfirst"),
        ModifierDef(name = "link", description = "Anchor tag.", takesArguments = true,
            parameters = listOf(
                ModifierParam("text", "Anchor text.", optional = true),
                ModifierParam("title", "title attribute.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/link"),
        ModifierDef(name = "list", description = "Ul markup.", docUrl = "https://statamic.dev/modifiers/list"),
        ModifierDef(name = "macro", description = "Invoke macro.", takesArguments = true,
            parameters = listOf(
                ModifierParam("name", "Macro to invoke."),
            ),
            docUrl = "https://statamic.dev/modifiers/macro"),
        ModifierDef(name = "mark", description = "Highlight term.", takesArguments = true,
            parameters = listOf(
                ModifierParam("term", "Text to wrap in <mark> tags."),
            ),
            docUrl = "https://statamic.dev/modifiers/mark"),
        ModifierDef(name = "md5", description = "MD5 hash.", docUrl = "https://statamic.dev/modifiers/md5"),
        ModifierDef(name = "minutes_ago", description = "Minutes since.", takesArguments = false, docUrl = "https://statamic.dev/modifiers/minutes_ago"),
        ModifierDef(name = "mod", description = "Modulo.", takesArguments = true,
            parameters = listOf(
                ModifierParam("value", "Divisor for the modulo."),
            ),
            docUrl = "https://statamic.dev/modifiers/mod"),
        ModifierDef(name = "modify_date", description = "Adjust date.", takesArguments = true,
            parameters = listOf(
                ModifierParam("modifier", "Relative string, e.g. '+1 day'."),
            ),
            docUrl = "https://statamic.dev/modifiers/modify_date"),
        ModifierDef(name = "months_ago", description = "Months since.", docUrl = "https://statamic.dev/modifiers/months_ago"),
        ModifierDef(name = "multiply", description = "Multiplication.", takesArguments = true,
            parameters = listOf(
                ModifierParam("value", "Number to multiply by."),
            ),
            docUrl = "https://statamic.dev/modifiers/multiply"),
        ModifierDef(name = "obfuscate", description = "Obfuscate text.", docUrl = "https://statamic.dev/modifiers/obfuscate"),
        ModifierDef(name = "obfuscate_email", description = "Obfuscate email.", docUrl = "https://statamic.dev/modifiers/obfuscate_email"),
        ModifierDef(name = "offset", description = "Skip items.", takesArguments = true,
            parameters = listOf(
                ModifierParam("count", "Number of leading items to skip."),
            ),
            docUrl = "https://statamic.dev/modifiers/offset"),
        ModifierDef(name = "ol", description = "Ordered list.", docUrl = "https://statamic.dev/modifiers/ol"),
        ModifierDef(name = "ul", description = "Unordered list markup.", docUrl = "https://statamic.dev/modifiers/ul"),
        ModifierDef(name = "option_list", description = "Select options.", docUrl = "https://statamic.dev/modifiers/option_list"),
        ModifierDef(name = "output", description = "Asset file contents.", docUrl = "https://statamic.dev/modifiers/output"),
        ModifierDef(name = "overlaps", description = "Arrays share a value.", takesArguments = true,
            parameters = listOf(
                ModifierParam("values", "Other array to intersect with."),
            ),
            docUrl = "https://statamic.dev/modifiers/overlaps"),
        ModifierDef(name = "pad", description = "Pad array.", takesArguments = true,
            parameters = listOf(
                ModifierParam("size", "Target array size."),
                ModifierParam("value", "Value to pad with.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/pad"),
        ModifierDef(name = "parse_url", description = "URL parts.", takesArguments = true,
            parameters = listOf(
                ModifierParam("component", "Specific URL part to return.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/parse_url"),
        ModifierDef(name = "partial", description = "Render partial.", takesArguments = true,
            parameters = listOf(
                ModifierParam("name", "Partial template to render."),
            ),
            docUrl = "https://statamic.dev/modifiers/partial"),
        ModifierDef(name = "pathinfo", description = "Path info.", takesArguments = true,
            parameters = listOf(
                ModifierParam("component", "Specific path part to return.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/pathinfo"),
        ModifierDef(name = "piped", description = "Pipe through callable.", takesArguments = true,
            parameters = listOf(
                ModifierParam("callable", "Callable/modifier name to pipe through."),
            ),
            docUrl = "https://statamic.dev/modifiers/piped"),
        ModifierDef(name = "plural", description = "Pluralize.", docUrl = "https://statamic.dev/modifiers/plural"),
        ModifierDef(name = "random", description = "Random item.", docUrl = "https://statamic.dev/modifiers/random"),
        ModifierDef(name = "rawurlencode", description = "Raw URL-encode.", docUrl = "https://statamic.dev/modifiers/rawurlencode"),
        ModifierDef(name = "rawurlencode_except_slashes", description = "Encode except slashes.", docUrl = "https://statamic.dev/modifiers/rawurlencode_except_slashes", introducedIn = 6),
        ModifierDef(name = "ray", description = "Ray debug.", docUrl = "https://statamic.dev/modifiers/ray"),
        ModifierDef(name = "read_time", description = "Reading time.", takesArguments = true,
            parameters = listOf(
                ModifierParam("wpm", "Words read per minute.", optional = true, default = "200"),
            ),
            docUrl = "https://statamic.dev/modifiers/read_time"),
        ModifierDef(name = "regex_mark", description = "Highlight regex.", takesArguments = true,
            parameters = listOf(
                ModifierParam("pattern", "Regex whose matches are wrapped in <mark>."),
            ),
            docUrl = "https://statamic.dev/modifiers/regex_mark"),
        ModifierDef(name = "regex_replace", description = "Regex replace.", takesArguments = true,
            parameters = listOf(
                ModifierParam("pattern", "Regex to match."),
                ModifierParam("replacement", "Replacement string."),
            ),
            docUrl = "https://statamic.dev/modifiers/regex_replace"),
        ModifierDef(name = "remove_left", description = "Strip prefix.", takesArguments = true,
            parameters = listOf(
                ModifierParam("prefix", "Prefix to strip if present."),
            ),
            docUrl = "https://statamic.dev/modifiers/remove_left"),
        ModifierDef(name = "remove_right", description = "Strip suffix.", takesArguments = true,
            parameters = listOf(
                ModifierParam("suffix", "Suffix to strip if present."),
            ),
            docUrl = "https://statamic.dev/modifiers/remove_right"),
        ModifierDef(name = "repeat", description = "Repeat string.", takesArguments = true,
            parameters = listOf(
                ModifierParam("times", "How many times to repeat the string."),
            ),
            docUrl = "https://statamic.dev/modifiers/repeat"),
        ModifierDef(name = "resolve", description = "Resolve relations.", docUrl = "https://statamic.dev/modifiers/resolve"),
        ModifierDef(name = "round", description = "Round to precision.", takesArguments = true,
            parameters = listOf(
                ModifierParam("precision", "Decimal places.", optional = true, default = "0"),
            ),
            docUrl = "https://statamic.dev/modifiers/round"),
        ModifierDef(name = "safe_truncate", description = "Word-safe truncate.", takesArguments = true,
            parameters = listOf(
                ModifierParam("length", "Maximum length, not splitting words."),
                ModifierParam("ellipsis", "Appended when truncated.", optional = true, default = "'…'"),
            ),
            docUrl = "https://statamic.dev/modifiers/safe_truncate"),
        ModifierDef(name = "sanitize", description = "Sanitize HTML.", docUrl = "https://statamic.dev/modifiers/sanitize"),
        ModifierDef(name = "scope", description = "Apply query scope.", takesArguments = true,
            parameters = listOf(
                ModifierParam("name", "Query scope to apply."),
            ),
            docUrl = "https://statamic.dev/modifiers/scope"),
        ModifierDef(name = "seconds_ago", description = "Seconds since.", docUrl = "https://statamic.dev/modifiers/seconds_ago"),
        ModifierDef(name = "segment", description = "URL segment.", takesArguments = true,
            parameters = listOf(
                ModifierParam("index", "1-based URL segment to return."),
            ),
            docUrl = "https://statamic.dev/modifiers/segment"),
        ModifierDef(name = "select", description = "Select property.", takesArguments = true,
            parameters = listOf(
                ModifierParam("keys", "One or more properties to keep."),
            ),
            docUrl = "https://statamic.dev/modifiers/select"),
        ModifierDef(name = "sentence_list", description = "Sentence list.", docUrl = "https://statamic.dev/modifiers/sentence_list"),
        ModifierDef(name = "shuffle", description = "Shuffle.", docUrl = "https://statamic.dev/modifiers/shuffle"),
        ModifierDef(name = "singular", description = "Singularize.", docUrl = "https://statamic.dev/modifiers/singular"),
        ModifierDef(name = "smartypants", description = "Smart typography.", docUrl = "https://statamic.dev/modifiers/smartypants"),
        ModifierDef(name = "snake", description = "To snake_case.", docUrl = "https://statamic.dev/modifiers/snake"),
        ModifierDef(name = "spaceless", description = "Strip inter-tag space.", docUrl = "https://statamic.dev/modifiers/spaceless"),
        ModifierDef(name = "split", description = "Split string.", takesArguments = true,
            parameters = listOf(
                ModifierParam("length", "Characters per chunk.", optional = true, default = "1"),
            ),
            docUrl = "https://statamic.dev/modifiers/split"),
        ModifierDef(name = "str_pad_left", description = "Left-pad string.", takesArguments = true,
            parameters = listOf(
                ModifierParam("length", "Target total length."),
                ModifierParam("pad", "Padding string.", optional = true, default = "' '"),
            ),
            docUrl = "https://statamic.dev/modifiers/str_pad_left"),
        ModifierDef(name = "studly", description = "To StudlyCase.", docUrl = "https://statamic.dev/modifiers/studly"),
        ModifierDef(name = "substr", description = "Substring.", takesArguments = true,
            parameters = listOf(
                ModifierParam("start", "Start index (negative counts from the end)."),
                ModifierParam("length", "Number of characters to take.", optional = true),
            ),
            docUrl = "https://statamic.dev/modifiers/substr"),
        ModifierDef(name = "subtract", description = "Subtraction.", takesArguments = true,
            parameters = listOf(
                ModifierParam("value", "Number to subtract."),
            ),
            docUrl = "https://statamic.dev/modifiers/subtract"),
        ModifierDef(name = "sum", description = "Sum values.", docUrl = "https://statamic.dev/modifiers/sum"),
        ModifierDef(name = "surround", description = "Wrap with delimiters.", takesArguments = true,
            parameters = listOf(
                ModifierParam("delimiter", "Wrapped before and after the value."),
            ),
            docUrl = "https://statamic.dev/modifiers/surround"),
        ModifierDef(name = "swap_case", description = "Swap case.", docUrl = "https://statamic.dev/modifiers/swap_case"),
        ModifierDef(name = "table", description = "HTML table.", docUrl = "https://statamic.dev/modifiers/table"),
        ModifierDef(name = "tidy", description = "Tidy HTML.", docUrl = "https://statamic.dev/modifiers/tidy"),
        ModifierDef(name = "timezone", description = "Convert timezone.", takesArguments = true,
            parameters = listOf(
                ModifierParam("timezone", "Target timezone, e.g. 'Europe/Berlin'."),
            ),
            docUrl = "https://statamic.dev/modifiers/timezone"),
        ModifierDef(name = "to_qs", description = "To query string.", docUrl = "https://statamic.dev/modifiers/to_qs"),
        ModifierDef(name = "to_spaces", description = "Tabs to spaces.", takesArguments = true,
            parameters = listOf(
                ModifierParam("width", "Spaces per tab.", optional = true, default = "4"),
            ),
            docUrl = "https://statamic.dev/modifiers/to_spaces"),
        ModifierDef(name = "to_tabs", description = "Spaces to tabs.", takesArguments = true,
            parameters = listOf(
                ModifierParam("width", "Spaces per tab.", optional = true, default = "4"),
            ),
            docUrl = "https://statamic.dev/modifiers/to_tabs"),
        ModifierDef(name = "trim", description = "Trim whitespace.", docUrl = "https://statamic.dev/modifiers/trim"),
        ModifierDef(name = "underscored", description = "To underscored.", docUrl = "https://statamic.dev/modifiers/underscored"),
        ModifierDef(name = "unique", description = "Dedupe.", docUrl = "https://statamic.dev/modifiers/unique"),
        ModifierDef(name = "urldecode", description = "URL-decode.", docUrl = "https://statamic.dev/modifiers/urldecode"),
        ModifierDef(name = "urlencode", description = "URL-encode.", docUrl = "https://statamic.dev/modifiers/urlencode"),
        ModifierDef(name = "urlencode_except_slashes", description = "Encode except slashes.", docUrl = "https://statamic.dev/modifiers/urlencode_except_slashes", introducedIn = 6),
        ModifierDef(name = "values", description = "Array values.", docUrl = "https://statamic.dev/modifiers/values"),
        ModifierDef(name = "weeks_ago", description = "Weeks since.", docUrl = "https://statamic.dev/modifiers/weeks_ago"),
        ModifierDef(name = "where_in", description = "Filter an array to items whose key matches one of the given values.", takesArguments = true,
            parameters = listOf(
                ModifierParam("key", "Item property to test."),
                ModifierParam("values", "List of allowed values."),
            ),
            docUrl = "https://statamic.dev/modifiers/where-in"),
        ModifierDef(name = "widont", description = "Prevent widows.", docUrl = "https://statamic.dev/modifiers/widont"),
        ModifierDef(name = "word_count", description = "Word count.", docUrl = "https://statamic.dev/modifiers/word_count"),
        ModifierDef(name = "wrap", description = "Wrap with HTML.", takesArguments = true,
            parameters = listOf(
                ModifierParam("tag", "HTML tag name to wrap the value in."),
            ),
            docUrl = "https://statamic.dev/modifiers/wrap"),
        ModifierDef(name = "years_ago", description = "Years since.", docUrl = "https://statamic.dev/modifiers/years_ago")
    )
}
