{
  parserClass="com.github.balotias.intellijantlers.parser.AntlersParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Antlers"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.balotias.intellijantlers.psi"
  psiImplPackage="com.github.balotias.intellijantlers.psi.impl"

  elementTypeHolderClass="com.github.balotias.intellijantlers.psi.AntlersTypes"
  elementTypeClass="com.github.balotias.intellijantlers.psi.AntlersElementType"
  tokenTypeClass="com.github.balotias.intellijantlers.psi.AntlersTokenType"
  parserUtilClass="com.github.balotias.intellijantlers.parser.AntlersParserUtil"

  tokens = [
    T_OUTER_HTML="T_OUTER_HTML"
    T_FRONTMATTER_FENCE="T_FRONTMATTER_FENCE"
    T_FRONTMATTER_TEXT="T_FRONTMATTER_TEXT"
    T_LDOUBLE="{{"
    T_RDOUBLE="}}"
    T_COMMENT_OPEN="{{#"
    T_COMMENT_CLOSE="#}}"
    T_COMMENT_TEXT="T_COMMENT_TEXT"
    T_PHP_RAW_OPEN="{{?"
    T_PHP_RAW_CLOSE="?}}"
    T_PHP_ECHO_OPEN="{{$"
    T_PHP_ECHO_CLOSE="$}}"
    T_PHP_TEXT="T_PHP_TEXT"
    T_PHP_TAG_OPEN="<?php"
    T_PHP_ECHO_TAG_OPEN="<?="
    T_PHP_TAG_CLOSE="?>"
    T_NOPARSE_OPEN="T_NOPARSE_OPEN"
    T_NOPARSE_CLOSE="T_NOPARSE_CLOSE"
    T_NOPARSE_TEXT="T_NOPARSE_TEXT"
    T_IDENT="T_IDENT"
    T_STRING="T_STRING"
    T_NUMBER="T_NUMBER"
    T_OP="T_OP"
    T_PIPE="|"
    T_SLASH="/"
    T_COLON=":"
    T_DOT="."
    T_COMMA=","
    T_SEMICOLON=";"
    T_EQUALS="="
    T_ARROW="=>"
    T_LPAREN="("
    T_RPAREN=")"
    T_LBRACKET="["
    T_RBRACKET="]"
    T_LBRACE="{"
    T_RBRACE="}"
    T_AT="@"
    T_DOLLAR="$"
    T_PERCENT="%"
    T_WS="T_WS"
  ]
}

antlersFile ::= frontMatter? node_*

frontMatter ::= T_FRONTMATTER_FENCE frontMatterBody? T_FRONTMATTER_FENCE?
frontMatterBody ::= T_FRONTMATTER_TEXT+ {
  mixin="com.github.balotias.intellijantlers.psi.AntlersFrontMatterBodyMixin"
  implements="com.intellij.psi.PsiLanguageInjectionHost"
}

private node_ ::= comment | phpBlock | noparseBlock | statement | outerHtml

outerHtml ::= T_OUTER_HTML

comment ::= T_COMMENT_OPEN T_COMMENT_TEXT? T_COMMENT_CLOSE { pin=1 }

phpBlock ::= phpRawBlock | phpEchoBlock | phpTagBlock | phpEchoTagBlock
phpRawBlock     ::= T_PHP_RAW_OPEN       phpBlockBody? T_PHP_RAW_CLOSE
phpEchoBlock    ::= T_PHP_ECHO_OPEN      phpBlockBody? T_PHP_ECHO_CLOSE
phpTagBlock     ::= T_PHP_TAG_OPEN       phpBlockBody? T_PHP_TAG_CLOSE?
phpEchoTagBlock ::= T_PHP_ECHO_TAG_OPEN  phpBlockBody? T_PHP_TAG_CLOSE?
phpBlockBody ::= T_PHP_TEXT+ {
  mixin="com.github.balotias.intellijantlers.psi.AntlersPhpBlockBodyMixin"
  implements="com.intellij.psi.PsiLanguageInjectionHost"
}

noparseBlock ::= T_NOPARSE_OPEN T_NOPARSE_TEXT* T_NOPARSE_CLOSE { pin=1 }

statement ::= T_LDOUBLE body? T_RDOUBLE {
  pin=1
  recoverWhile=statement_recover
}
private statement_recover ::= !(T_RDOUBLE | T_LDOUBLE | T_OUTER_HTML | T_COMMENT_OPEN | T_NOPARSE_OPEN | T_PHP_RAW_OPEN | T_PHP_ECHO_OPEN)

private body ::= closingTag | condition | expr_

// `{{ /tag }}`, with the optional `%` tag-disambiguation prefix and slash-separated path segments
// (`{{ /partial:components/notification }}`). The slash tail mirrors the loose path tokens the opening
// form already consumes via `tail_*`.
closingTag ::= T_SLASH T_PERCENT? namePath? closerPathSegment_* {
  mixin="com.github.balotias.intellijantlers.psi.AntlersClosingTagMixin"
}
private closerPathSegment_ ::= T_SLASH pathSegment?

condition ::= <<atConditionKeyword>> conditionKeyword (modifier | exprToken_)* {
  mixin="com.github.balotias.intellijantlers.psi.AntlersConditionMixin"
}
private conditionKeyword ::= T_IDENT

// A leading `%` disambiguates a tag from a same-named variable (`{{ %form:fields }}`).
private expr_ ::= T_PERCENT? namePath tail_* | tail_+

private tail_ ::= parameter | modifier | exprToken_

namePath ::= pathSegment ((T_COLON pathSegment !T_EQUALS) | T_DOT pathSegment | bracketAccess)* {
  mixin="com.github.balotias.intellijantlers.psi.AntlersNamePathMixin"
}
private pathSegment ::= T_DOLLAR? (T_IDENT | T_NUMBER)
bracketAccess ::= T_LBRACKET groupToken_* T_RBRACKET

parameter ::= boundParameter_ | staticParameter_ {
  mixin="com.github.balotias.intellijantlers.psi.AntlersParameterMixin"
}
private boundParameter_ ::= T_COLON T_DOLLAR? T_IDENT (T_EQUALS paramValue)?
                          | T_DOLLAR T_IDENT
private staticParameter_ ::= T_IDENT T_EQUALS paramValue
private paramValue ::= T_STRING | (T_LBRACE groupToken_* T_RBRACE) | T_NUMBER | namePath

modifier ::= T_PIPE T_IDENT ((T_LPAREN argList? T_RPAREN) | (T_COLON modifierArg_)+)? {
  mixin="com.github.balotias.intellijantlers.psi.AntlersModifierMixin"
}
private argList ::= exprToken_ (T_COMMA exprToken_)*
private modifierArg_ ::= T_STRING | T_NUMBER | T_DOLLAR? T_IDENT

private exprToken_ ::=
    T_OP | T_STRING | T_NUMBER | T_ARROW | T_DOT | T_COLON | T_COMMA | T_SEMICOLON
  | T_EQUALS | T_DOLLAR | T_PERCENT | T_AT | T_LPAREN | T_RPAREN | T_LBRACKET | T_RBRACKET
  | T_LBRACE | T_RBRACE | T_IDENT | T_SLASH

private groupToken_ ::=
    T_OP | T_STRING | T_NUMBER | T_ARROW | T_DOT | T_COLON | T_COMMA | T_SEMICOLON
  | T_EQUALS | T_DOLLAR | T_PERCENT | T_AT | T_LPAREN | T_RPAREN | T_LBRACKET
  | T_LBRACE | T_IDENT | T_SLASH
